# Generated by Django 4.2.4 on 2023-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='movies/static')),
                ('cardname', models.CharField(max_length=20)),
                ('genres', models.CharField(max_length=50)),
            ],
        ),
    ]
