# Generated by Django 4.2.4 on 2023-09-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0003_alter_cardmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='category',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
