# Generated by Django 4.2.4 on 2023-09-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0004_cardmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='youtube',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
