# Generated by Django 4.2.4 on 2023-09-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0005_cardmodel_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='duration',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='language',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
