# Generated by Django 4.2.4 on 2023-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0007_cardmodel_about_cardmodel_castimg_cardmodel_castname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardmodel',
            old_name='castimg',
            new_name='castimg1',
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='castimg2',
            field=models.FileField(default=1, upload_to='seatwiseapp/static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='castimg3',
            field=models.FileField(default=1, upload_to='seatwiseapp/static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='castimg4',
            field=models.FileField(default=1, upload_to='seatwiseapp/static'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='castimg5',
            field=models.FileField(default=1, upload_to='seatwiseapp/static'),
            preserve_default=False,
        ),
    ]
