# Generated by Django 4.2.4 on 2023-09-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0009_rename_castname_cardmodel_castname1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodel',
            name='castimg1',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castimg2',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castimg3',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castimg4',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castimg5',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castname1',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castname2',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castname3',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castname4',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='castname5',
        ),
    ]
