# Generated by Django 4.2.4 on 2023-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0010_remove_cardmodel_castimg1_remove_cardmodel_castimg2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('selectedSeats', models.CharField(max_length=100)),
            ],
        ),
    ]
