# Generated by Django 4.2.4 on 2023-09-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0012_alter_seatselection_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatselection',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seatselection',
            name='time',
        ),
    ]
