# Generated by Django 4.2.4 on 2023-09-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0013_remove_seatselection_date_remove_seatselection_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatselection',
            old_name='selectedSeats',
            new_name='selectedseats',
        ),
        migrations.AddField(
            model_name='seatselection',
            name='movieid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
