# Generated by Django 4.2.4 on 2023-09-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0015_seatselection_seat_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatselection',
            name='seat_cost',
        ),
        migrations.AddField(
            model_name='seatselection',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
