# Generated by Django 4.2.4 on 2023-09-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0016_remove_seatselection_seat_cost_seatselection_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatselection',
            name='count',
        ),
    ]
