# Generated by Django 4.2.4 on 2023-10-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0018_remove_seatselection_movieid_seatselection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatselection',
            name='filmname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
