# Generated by Django 4.2.4 on 2023-10-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0019_seatselection_filmname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatselection',
            name='filmname',
        ),
    ]
