# Generated by Django 4.2.4 on 2023-11-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0020_remove_seatselection_filmname'),
    ]

    operations = [
        migrations.CreateModel(
            name='seatselection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=15)),
                ('selectedseats', models.CharField(max_length=100)),
                ('ticket_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatwiseapp.cardmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='SeatSelection',
        ),
    ]
