# Generated by Django 4.2.4 on 2023-11-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatwiseapp', '0022_remove_seatselection1_ticket_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
